apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applications
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - list:
              elements:
              - cluster: dev
                url: https://kubernetes.default.svc
          - git:
              repoURL: https://gitea.zengarden.space/zengarden-space/manifests.git
              revision: main
              directories:
              - path: "*"
  template:
    metadata:
      name: '{{.path.basename}}'
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          allowEmpty: true
          selfHeal: true
      source:
        repoURL: https://gitea.zengarden.space/zengarden-space/manifests.git
        targetRevision: main
        path: '{{.path.path}}/{{.cluster}}'
      destination:
        server: '{{.url}}'
        namespace: '{{.path.basenameNormalized}}'