apiVersion: v1
kind: ServiceAccount
metadata:
  name: retroboard
  labels:
    helm.sh/chart: retroboard-0.1.0
    app.kubernetes.io/name: retroboard
    app.kubernetes.io/instance: retroboard
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/managed-by: Helm
---
apiVersion: v1
kind: Service
metadata:
  name: retroboard
  labels:
    helm.sh/chart: retroboard-0.1.0
    app.kubernetes.io/name: retroboard
    app.kubernetes.io/instance: retroboard
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 5173
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: retroboard
    app.kubernetes.io/instance: retroboard
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: retroboard
  labels:
    helm.sh/chart: retroboard-0.1.0
    app.kubernetes.io/name: retroboard
    app.kubernetes.io/instance: retroboard
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: retroboard
      app.kubernetes.io/instance: retroboard
  template:
    metadata:
      labels:
        app.kubernetes.io/name: retroboard
        app.kubernetes.io/instance: retroboard
    spec:
      serviceAccountName: retroboard
      securityContext:
        fsGroup: 2000
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: retroboard
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
        image: gitea.homelab.int.zengarden.space/zengarden-space/retroboard:sha-d85ed6e
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 5173
          protocol: TCP
        env: null
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: var-cache-nginx
          mountPath: /var/cache/nginx
        - name: var-run
          mountPath: /var/run
      volumes:
      - name: tmp
        emptyDir: {}
      - name: var-cache-nginx
        emptyDir: {}
      - name: var-run
        emptyDir: {}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - retroboard
              topologyKey: kubernetes.io/hostname
            weight: 100
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: retroboard
  labels:
    helm.sh/chart: retroboard-0.1.0
    app.kubernetes.io/name: retroboard
    app.kubernetes.io/instance: retroboard
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/managed-by: Helm
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: retroboard
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
---
apiVersion: networking.zengarden.space/v1
kind: PartialIngress
metadata:
  name: retroboard
  labels:
    helm.sh/chart: retroboard-0.1.0
    app.kubernetes.io/name: retroboard
    app.kubernetes.io/instance: retroboard
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/managed-by: Helm
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
spec:
  ingressClassName: internal
  tls:
  - hosts:
    - retroboard-2e339a83.homelab.int.zengarden.space
    secretName: retroboard-2e339a83-homelab-tls
  rules:
  - host: retroboard-2e339a83.homelab.int.zengarden.space
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: retroboard
            port:
              number: 80
