---
# Source: practical-app-frontend/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: practical-app-frontend
  labels:
    helm.sh/chart: practical-app-frontend-0.1.0
    app.kubernetes.io/name: practical-app-frontend
    app.kubernetes.io/instance: practical-app-frontend
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
---
# Source: practical-app-frontend/templates/serviceaccount.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: practical-app-frontend-job-watcher
  labels:
    helm.sh/chart: practical-app-frontend-0.1.0
    app.kubernetes.io/name: practical-app-frontend
    app.kubernetes.io/instance: practical-app-frontend
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch"]
---
# Source: practical-app-frontend/templates/serviceaccount.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: practical-app-frontend-job-watcher
  labels:
    helm.sh/chart: practical-app-frontend-0.1.0
    app.kubernetes.io/name: practical-app-frontend
    app.kubernetes.io/instance: practical-app-frontend
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
subjects:
- kind: ServiceAccount
  name: practical-app-frontend
  namespace: prod-practical-app-frontend
roleRef:
  kind: Role
  name: practical-app-frontend-job-watcher
  apiGroup: rbac.authorization.k8s.io
---
# Source: practical-app-frontend/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: practical-app-frontend
  labels:
    helm.sh/chart: practical-app-frontend-0.1.0
    app.kubernetes.io/name: practical-app-frontend
    app.kubernetes.io/instance: practical-app-frontend
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: practical-app-frontend
    app.kubernetes.io/instance: practical-app-frontend
---
# Source: practical-app-frontend/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: practical-app-frontend
  labels:
    helm.sh/chart: practical-app-frontend-0.1.0
    app.kubernetes.io/name: practical-app-frontend
    app.kubernetes.io/instance: practical-app-frontend
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: practical-app-frontend
      app.kubernetes.io/instance: practical-app-frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: practical-app-frontend
        app.kubernetes.io/instance: practical-app-frontend
    spec:
      serviceAccountName: practical-app-frontend
      securityContext:
        fsGroup: 2000
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: practical-app-frontend
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
          image: "gitea.homelab.int.zengarden.space/zengarden-space/practical-app-frontend:sha-8fda61d"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: "NODE_ENV"
              value: "production"
          envFrom:
            - secretRef:
                name: practical-app-frontend-envs-secrets
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 128Mi
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - practical-app-frontend
              topologyKey: kubernetes.io/hostname
            weight: 100
---
# Source: practical-app-frontend/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: practical-app-frontend
  labels:
    helm.sh/chart: practical-app-frontend-0.1.0
    app.kubernetes.io/name: practical-app-frontend
    app.kubernetes.io/instance: practical-app-frontend
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: external
  rules:
    - host: "practical-app-prod.zengarden.space"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: practical-app-frontend
                port:
                  number: 80
---
# Source: practical-app-frontend/templates/external-secrets.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: practical-app-frontend-envs-secrets
  labels:
    helm.sh/chart: practical-app-frontend-0.1.0
    app.kubernetes.io/name: practical-app-frontend
    app.kubernetes.io/instance: practical-app-frontend
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: secrets
    kind: ClusterSecretStore
  target:
    name: practical-app-frontend-envs-secrets
    creationPolicy: Owner
    template:
      data:
        
        NEXT_PUBLIC_API_URL: '{{ .practicalAppApiUrl }}'
  dataFrom:
    - extract:
        key: "prod-practical-app-frontend"
---
# Source: practical-app-frontend/templates/service-monitor.yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: practical-app-frontend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: practical-app-frontend
      app.kubernetes.io/instance: practical-app-frontend
  endpoints:
    - port: http
      interval: 15s
      path: /metrics
      scrapeTimeout: 10s
