apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: homelab-ci-applications
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://gitea.homelab.int.zengarden.space/zengarden-space/manifests.git
        revision: main
        directories:
        - path: "homelab/ci-*/*"
  template:
    metadata:
      name: 'homelab.{{.path.basename}}.{{ .path.segments 1 }}'
    spec:
      project: apps
      syncPolicy:
        automated:
          prune: true
          allowEmpty: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      source:
        repoURL: https://gitea.homelab.int.zengarden.space/zengarden-space/manifests.git
        targetRevision: main
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ .path.segments 1 }}-{{.path.basenameNormalized}}'