---
# Source: devbox/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: devbox
  labels:
    helm.sh/chart: devbox-0.1.0
    app.kubernetes.io/name: devbox
    app.kubernetes.io/instance: devbox
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance-user: "oleksiyp"
---
# Source: devbox/templates/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: devbox-workspace
  labels:
    helm.sh/chart: devbox-0.1.0
    app.kubernetes.io/name: devbox
    app.kubernetes.io/instance: devbox
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance-user: "oleksiyp"
    app.kubernetes.io/component: workspace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
# Source: devbox/templates/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: devbox-settings
  labels:
    helm.sh/chart: devbox-0.1.0
    app.kubernetes.io/name: devbox
    app.kubernetes.io/instance: devbox
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance-user: "oleksiyp"
    app.kubernetes.io/component: settings
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
# Source: devbox/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: devbox
  labels:
    helm.sh/chart: devbox-0.1.0
    app.kubernetes.io/name: devbox
    app.kubernetes.io/instance: devbox
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance-user: "oleksiyp"
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: devbox
    app.kubernetes.io/instance: devbox
---
# Source: devbox/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devbox
  labels:
    helm.sh/chart: devbox-0.1.0
    app.kubernetes.io/name: devbox
    app.kubernetes.io/instance: devbox
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance-user: "oleksiyp"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: devbox
      app.kubernetes.io/instance: devbox
  template:
    metadata:
      labels:
        app.kubernetes.io/name: devbox
        app.kubernetes.io/instance: devbox
    spec:
      serviceAccountName: devbox
      securityContext:
        fsGroup: 1001
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: devbox
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 1001
          image: "gitea.homelab.int.zengarden.space/zengarden-space/devbox:sha-fba429f"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: "GIT_AUTHOR_EMAIL"
              value: "oleksiy.pylypenko@gmail.com"
            - name: "GIT_AUTHOR_NAME"
              value: "Oleksii Pylypenko"
            - name: "GIT_COMMITTER_EMAIL"
              value: "oleksiy.pylypenko@gmail.com"
            - name: "GIT_COMMITTER_NAME"
              value: "Oleksii Pylypenko"
          volumeMounts:
            - name: workspace
              mountPath: /home/dev/workspace
            - name: settings
              mountPath: /home/dev/.openvscode-server
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
          resources:
            limits:
              cpu: 4000m
              memory: 8Gi
            requests:
              cpu: 1000m
              memory: 2Gi
      volumes:
        - name: workspace
          persistentVolumeClaim:
            claimName: devbox-workspace
        - name: settings
          persistentVolumeClaim:
            claimName: devbox-settings
---
# Source: devbox/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devbox
  labels:
    helm.sh/chart: devbox-0.1.0
    app.kubernetes.io/name: devbox
    app.kubernetes.io/instance: devbox
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance-user: "oleksiyp"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    # WebSocket support for VS Code
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/websocket-services: devbox
spec:
  ingressClassName: internal
  tls:
    - hosts:
        - "code-oleksiyp.homelab.int.zengarden.space"
      secretName: code-oleksiyp-tls
  rules:
    - host: "code-oleksiyp.homelab.int.zengarden.space"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: devbox
                port:
                  number: 80
